services:
  client:
    build: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    env_file: 
      - ./client/.env
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    depends_on:
      - server
      - socket

  server:
    build: ./server
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./server/config/config.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  socket:
    build: ./socket
    container_name: chat
    ports:
      - "4000:4000"
    env_file:
      - ./socket/config/config.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"