name: Globemart Workflow

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.client_changed.outputs.client }}
      server_changed: ${{ steps.server_changed.outputs.server }}
      socket_changed: ${{ steps.socket_changed.outputs.socket }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for changes in client
        id: client_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'

      - name: Check for changes in server
        id: server_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'

      - name: Check for changes in socket
        id: socket_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            socket:
              - 'socket/**'

  client:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.client_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file for client
        run: |
          cd client
          echo "VITE_APP_CURRENCY_API_KEY=${{ secrets.VITE_APP_CURRENCY_API_KEY }}" >> .env

          echo "VITE_APP_CURRENCY_SECRET_KEY=${{ secrets.VITE_APP_CURRENCY_SECRET_KEY }}" >> .env

          echo "VITE_APP_USER_LOCATION=${{ secrets.VITE_APP_USER_LOCATION }}" >> .env

          echo "VITE_APP_BACKEND_URL=${{ secrets.VITE_APP_BACKEND_URL }}" >> .env

          echo "VITE_APP_SOCKET_BACKEND_URL=${{ secrets.VITE_APP_SOCKET_BACKEND_URL }}" >> .env

          echo "VITE_APP_NODE_ENV=${{ secrets.VITE_APP_NODE_ENV }}" >> .env

      - name: Creating Docker Image
        run: |
          cd client
          sudo docker build -t venkatreddy366/globemart-client .

      - name: Pushing image to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker push venkatreddy366/globemart-client

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 2m
          command_timeout: 10m
          script: |
            cd /home/ubuntu/globemart
            sudo docker pull venkatreddy366/globemart-client
            sudo docker compose up -d --no-deps client
            echo "Deployment completed"

  server:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.server_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: |
          cd server
          sudo docker build -t venkatreddy366/globemart-server .

      - name: Pushing image to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker push venkatreddy366/globemart-server

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 2m
          command_timeout: 10m
          script: |
            cd /home/ubuntu/globemart
            sudo docker pull venkatreddy366/globemart-server
            sudo docker compose up -d --no-deps server
            echo "Deployment completed"

  socket:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.socket_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: |
          cd socket
          sudo docker build -t venkatreddy366/globemart-socket .

      - name: Pushing image to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker push venkatreddy366/globemart-socket

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 2m
          command_timeout: 10m
          script: |
            cd /home/ubuntu/globemart
            sudo docker pull venkatreddy366/globemart-socket
            sudo docker compose up -d --no-deps socket
            echo "Deployment completed"
