name: Globemart Workflow

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      client_changed: ${{ steps.client_changed.outputs.client }}
      server_changed: ${{ steps.server_changed.outputs.server }}
      socket_changed: ${{ steps.socket_changed.outputs.socket }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check for changes in client
        id: client_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            client:
              - 'client/**'

      - name: Check for changes in server
        id: server_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            server:
              - 'server/**'

      - name: Check for changes in socket
        id: socket_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            socket:
              - 'socket/**'

  client:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.client_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: |
          cd client
          sudo docker build -t venkatreddy366/globemart-client .

      - name: Pushing image to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker push venkatreddy366/globemart-client

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull venkatreddy366/globemart-client
            cd /home/ubuntu/globemart
            sudo docker compose up -d --no-deps client

  server:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.server_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: |
          cd server
          sudo docker build -t venkatreddy366/globemart-server .

      - name: Pushing image to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker push venkatreddy366/globemart-server

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull venkatreddy366/globemart-server
            cd /home/ubuntu/globemart
            sudo docker compose up -d --no-deps server

  socket:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.socket_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Creating Docker Image
        run: |
          cd socket
          sudo docker build -t venkatreddy366/globemart-socket .

      - name: Pushing image to dockerhub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          sudo docker push venkatreddy366/globemart-socket

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull venkatreddy366/globemart-socket
            cd /home/ubuntu/globemart
            sudo docker compose up -d --no-deps socket
